<?xml version="1.0" encoding="UTF-8"?>
<PlexilPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:tr="extended-plexil-translator"
            FileName="/home/charles/plexil-4.0.1/examples/basic/plexil_test/Test.ple">
   <GlobalDeclarations LineNo="2" ColNo="0">
      <CommandDeclaration LineNo="2" ColNo="0">
         <Name>debugMsg</Name>
         <Parameter>
            <Name>msg</Name>
            <Type>String</Type>
         </Parameter>
      </CommandDeclaration>
      <CommandDeclaration LineNo="3" ColNo="0">
         <Name>drive</Name>
      </CommandDeclaration>
      <CommandDeclaration LineNo="4" ColNo="0">
         <Name>reverseAndTurn</Name>
      </CommandDeclaration>
      <CommandDeclaration LineNo="5" ColNo="0">
         <Name>dock</Name>
      </CommandDeclaration>
      <StateDeclaration LineNo="7" ColNo="5">
         <Name>wall_sensor</Name>
         <Return>
            <Name>_return_0</Name>
            <Type>Real</Type>
         </Return>
      </StateDeclaration>
      <StateDeclaration LineNo="8" ColNo="5">
         <Name>left_sensor</Name>
         <Return>
            <Name>_return_0</Name>
            <Type>Real</Type>
         </Return>
      </StateDeclaration>
      <StateDeclaration LineNo="9" ColNo="5">
         <Name>leftfront_sensor</Name>
         <Return>
            <Name>_return_0</Name>
            <Type>Real</Type>
         </Return>
      </StateDeclaration>
      <StateDeclaration LineNo="10" ColNo="5">
         <Name>right_sensor</Name>
         <Return>
            <Name>_return_0</Name>
            <Type>Real</Type>
         </Return>
      </StateDeclaration>
      <StateDeclaration LineNo="11" ColNo="5">
         <Name>rightfront_sensor</Name>
         <Return>
            <Name>_return_0</Name>
            <Type>Real</Type>
         </Return>
      </StateDeclaration>
   </GlobalDeclarations>
   <Node NodeType="NodeList" epx="Concurrence" LineNo="14" ColNo="6">
      <NodeId>Main</NodeId>
      <VariableDeclarations>
         <DeclareVariable LineNo="15" ColNo="2">
            <Name>drive_done</Name>
            <Type>Boolean</Type>
            <InitialValue>
               <BooleanValue>false</BooleanValue>
            </InitialValue>
         </DeclareVariable>
         <DeclareVariable LineNo="16" ColNo="2">
            <Name>SENSOR_TOL</Name>
            <Type>Real</Type>
            <InitialValue>
               <RealValue>0.035</RealValue>
            </InitialValue>
         </DeclareVariable>
         <DeclareVariable LineNo="17" ColNo="2">
            <Name>SENSOR_MAX</Name>
            <Type>Real</Type>
            <InitialValue>
               <RealValue>0.04</RealValue>
            </InitialValue>
         </DeclareVariable>
      </VariableDeclarations>
      <EndCondition>
         <EQBoolean>
            <BooleanVariable>drive_done</BooleanVariable>
            <BooleanValue>true</BooleanValue>
         </EQBoolean>
      </EndCondition>
      <NodeBody>
         <NodeList>
            <Node NodeType="Command" LineNo="28" ColNo="4">
               <NodeId>DriveToWaypoint</NodeId>
               <RepeatCondition>
                  <EQBoolean>
                     <BooleanVariable>drive_done</BooleanVariable>
                     <BooleanValue>false</BooleanValue>
                  </EQBoolean>
               </RepeatCondition>
               <InvariantCondition>
                  <AND>
                     <LT>
                        <LookupNow>
                           <Name>
                              <StringValue>left_sensor</StringValue>
                           </Name>
                        </LookupNow>
                        <RealVariable>SENSOR_TOL</RealVariable>
                     </LT>
                     <LT>
                        <LookupNow>
                           <Name>
                              <StringValue>leftfront_sensor</StringValue>
                           </Name>
                        </LookupNow>
                        <RealVariable>SENSOR_TOL</RealVariable>
                     </LT>
                     <LT>
                        <LookupNow>
                           <Name>
                              <StringValue>right_sensor</StringValue>
                           </Name>
                        </LookupNow>
                        <RealVariable>SENSOR_TOL</RealVariable>
                     </LT>
                     <LT>
                        <LookupNow>
                           <Name>
                              <StringValue>rightfront_sensor</StringValue>
                           </Name>
                        </LookupNow>
                        <RealVariable>SENSOR_TOL</RealVariable>
                     </LT>
                  </AND>
               </InvariantCondition>
               <NodeBody>
                  <Command>
                     <Name>
                        <StringValue>drive</StringValue>
                     </Name>
                  </Command>
               </NodeBody>
            </Node>
            <Node NodeType="Command" LineNo="38" ColNo="4">
               <NodeId>TiltSensor</NodeId>
               <RepeatCondition>
                  <EQBoolean>
                     <BooleanVariable>drive_done</BooleanVariable>
                     <BooleanValue>false</BooleanValue>
                  </EQBoolean>
               </RepeatCondition>
               <StartCondition>
                  <AND>
                     <GT>
                        <LookupOnChange>
                           <Name>
                              <StringValue>left_sensor</StringValue>
                           </Name>
                        </LookupOnChange>
                        <RealVariable>SENSOR_TOL</RealVariable>
                     </GT>
                     <GT>
                        <LookupOnChange>
                           <Name>
                              <StringValue>leftfront_sensor</StringValue>
                           </Name>
                        </LookupOnChange>
                        <RealVariable>SENSOR_TOL</RealVariable>
                     </GT>
                     <GT>
                        <LookupOnChange>
                           <Name>
                              <StringValue>right_sensor</StringValue>
                           </Name>
                        </LookupOnChange>
                        <RealVariable>SENSOR_TOL</RealVariable>
                     </GT>
                     <GT>
                        <LookupOnChange>
                           <Name>
                              <StringValue>rightfront_sensor</StringValue>
                           </Name>
                        </LookupOnChange>
                        <RealVariable>SENSOR_TOL</RealVariable>
                     </GT>
                  </AND>
               </StartCondition>
               <NodeBody>
                  <Command>
                     <Name>
                        <StringValue>reverseAndTurn</StringValue>
                     </Name>
                  </Command>
               </NodeBody>
            </Node>
            <Node NodeType="Command" LineNo="45" ColNo="4">
               <NodeId>BumpSensor</NodeId>
               <RepeatCondition>
                  <EQBoolean>
                     <BooleanVariable>drive_done</BooleanVariable>
                     <BooleanValue>false</BooleanValue>
                  </EQBoolean>
               </RepeatCondition>
               <StartCondition>
                  <LT>
                     <LookupOnChange>
                        <Name>
                           <StringValue>wall_sensor</StringValue>
                        </Name>
                     </LookupOnChange>
                     <RealVariable>SENSOR_TOL</RealVariable>
                  </LT>
               </StartCondition>
               <NodeBody>
                  <Command>
                     <Name>
                        <StringValue>reverseAndTurn</StringValue>
                     </Name>
                  </Command>
               </NodeBody>
            </Node>
            <Node NodeType="NodeList" epx="Sequence" LineNo="51" ColNo="4">
               <NodeId>DriveToDock</NodeId>
               <StartCondition>
                  <BooleanValue>false</BooleanValue>
               </StartCondition>
               <InvariantCondition>
                  <NOT>
                     <OR>
                        <AND>
                           <EQInternal>
                              <NodeOutcomeVariable>
                                 <NodeRef dir="child">StartDock</NodeRef>
                              </NodeOutcomeVariable>
                              <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                           </EQInternal>
                           <EQInternal>
                              <NodeStateVariable>
                                 <NodeRef dir="child">StartDock</NodeRef>
                              </NodeStateVariable>
                              <NodeStateValue>FINISHED</NodeStateValue>
                           </EQInternal>
                        </AND>
                        <AND>
                           <EQInternal>
                              <NodeOutcomeVariable>
                                 <NodeRef dir="child">COMMAND__4</NodeRef>
                              </NodeOutcomeVariable>
                              <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                           </EQInternal>
                           <EQInternal>
                              <NodeStateVariable>
                                 <NodeRef dir="child">COMMAND__4</NodeRef>
                              </NodeStateVariable>
                              <NodeStateValue>FINISHED</NodeStateValue>
                           </EQInternal>
                        </AND>
                        <AND>
                           <EQInternal>
                              <NodeOutcomeVariable>
                                 <NodeRef dir="child">ASSIGNMENT__5</NodeRef>
                              </NodeOutcomeVariable>
                              <NodeOutcomeValue>FAILURE</NodeOutcomeValue>
                           </EQInternal>
                           <EQInternal>
                              <NodeStateVariable>
                                 <NodeRef dir="child">ASSIGNMENT__5</NodeRef>
                              </NodeStateVariable>
                              <NodeStateValue>FINISHED</NodeStateValue>
                           </EQInternal>
                        </AND>
                     </OR>
                  </NOT>
               </InvariantCondition>
               <NodeBody>
                  <NodeList>
                     <Node NodeType="Command" LineNo="54" ColNo="6">
                        <NodeId>StartDock</NodeId>
                        <EndCondition>
                           <EQInternal>
                              <NodeCommandHandleVariable>
                                 <NodeId>StartDock</NodeId>
                              </NodeCommandHandleVariable>
                              <NodeCommandHandleValue>COMMAND_SUCCESS</NodeCommandHandleValue>
                           </EQInternal>
                        </EndCondition>
                        <NodeBody>
                           <Command>
                              <Name>
                                 <StringValue>dock</StringValue>
                              </Name>
                           </Command>
                        </NodeBody>
                     </Node>
                     <Node NodeType="Command" LineNo="56" ColNo="4">
                        <NodeId>COMMAND__4</NodeId>
                        <StartCondition>
                           <EQInternal>
                              <NodeStateVariable>
                                 <NodeRef dir="sibling">StartDock</NodeRef>
                              </NodeStateVariable>
                              <NodeStateValue>FINISHED</NodeStateValue>
                           </EQInternal>
                        </StartCondition>
                        <NodeBody>
                           <Command>
                              <Name>
                                 <StringValue>debugMsg</StringValue>
                              </Name>
                              <Arguments LineNo="57" ColNo="14">
                                 <StringValue>MISSION COMPLETE</StringValue>
                              </Arguments>
                           </Command>
                        </NodeBody>
                     </Node>
                     <Node NodeType="Assignment" LineNo="58" ColNo="4">
                        <NodeId>ASSIGNMENT__5</NodeId>
                        <StartCondition>
                           <EQInternal>
                              <NodeStateVariable>
                                 <NodeRef dir="sibling">COMMAND__4</NodeRef>
                              </NodeStateVariable>
                              <NodeStateValue>FINISHED</NodeStateValue>
                           </EQInternal>
                        </StartCondition>
                        <NodeBody>
                           <Assignment>
                              <BooleanVariable>drive_done</BooleanVariable>
                              <BooleanRHS>
                                 <BooleanValue>true</BooleanValue>
                              </BooleanRHS>
                           </Assignment>
                        </NodeBody>
                     </Node>
                  </NodeList>
               </NodeBody>
            </Node>
         </NodeList>
      </NodeBody>
   </Node>
</PlexilPlan>